<a href="https://colab.research.google.com/github/sreepuli/DS/blob/main/Assignement_1(ML).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Perform Arithmatic Operations On Numpy arrays

In [2]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,5,6]]),
b=np.array([[7,8,9],[10,11,12]])
print("Addition:\n ",np.add(a,b))   # output [[[ 8 10 12] [14 16 18]]]
print("Subtraction:\n ",np.subtract(a,b))  #output [[[-6 -6 -6] [-6 -6 -6]]]
print("Multiplication:\n ",np.multiply(a,b))
print("Division:\n  ",np.divide(a,b))
print("squre root:\n ",np.sqrt(a))
print("Exponent:\n ",np.power(b,a))

Addition:
  [[[ 8 10 12]
  [14 16 18]]]
Subtraction:
  [[[-6 -6 -6]
  [-6 -6 -6]]]
Multiplication:
  [[[ 7 16 27]
  [40 55 72]]]
Division:
   [[[0.14285714 0.25       0.33333333]
  [0.4        0.45454545 0.5       ]]]
squre root:
  [[[1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974]]]
Exponent:
  [[[      7      64     729]
  [  10000  161051 2985984]]]


##Script to compute the mean and standard Deviation of Numpy Array

Mean and standard deviation are built in functions in numpy library these both comes under satistical operators

In [ ]:
x=np.array([1,2,3,4,5,6,7])
print("Mean = ",np.mean(x))
print("Standar Deviation = " ,np.std(x))


Mean =  4.0
Standar Deviation =  2.0


In [ ]:
#for rank 2 arrays
y=np.array([[1,2,3,],[4,5,6]])
print("Mean  = ",np.mean(y))
print("Standard Deviation = ",np.std(y))

Mean  =  3.5
Standard Deviation =  1.707825127659933


** We can use axis word in function to find Mean and standard Deviation along Rows and Coloums**

In [ ]:
z= np.array([[1, 2, 3], [4, 5, 6]])

overall_mean = np.mean(z)           # Mean of all elements
mean_along_rows = np.mean(z, axis=1)  # Mean along rows
mean_along_columns = np.mean(z, axis=0)  # Mean along columns
overall_std = np.std(z)           # Standard deviation of all elements
std_along_rows = np.std(z, axis=1)  # Standard deviation along rows
std_along_columns = np.std(z, axis=0)  # Standard deviation along columns

print("Overall Mean:", overall_mean)         # 3.5
print("Row-wise Mean:", mean_along_rows)     # [2. 5.]
print("Column-wise Mean:", mean_along_columns)  # [2.5 3.5 4.5]
print("Overall Standard Deviation:", overall_std)         # 1.707825127659933
print("Row-wise Standard Deviation:", std_along_rows)     # [0.81649658 0.81649658]
print("Column-wise Standard Deviation:", std_along_columns)  # [1.5 1.5 1.5]



Overall Mean: 3.5
Row-wise Mean: [2. 5.]
Column-wise Mean: [2.5 3.5 4.5]
Overall Standard Deviation: 1.707825127659933
Row-wise Standard Deviation: [0.81649658 0.81649658]
Column-wise Standard Deviation: [1.5 1.5 1.5]


##3.create a Numpy array of integers from 10 t0 50 with step size of 5

to create a numpy array of some integers we can use .arange() function
np.arange(start,stop,step).

In [ ]:
array=np.arange(10,51,5)
print(array)

[10 15 20 25 30 35 40 45 50]


In [ ]:
arr=np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


## 4.Reshape the array in to 2x4 matrix

we can reshape the above array by using reshape function

In [ ]:
array=np.arange(10,50,5)
reshaped_arr=array.reshape(2,4)
print(reshaped_arr)

[[10 15 20 25]
 [30 35 40 45]]


In [ ]:
reshaped_arr=array.reshape(4,2)
print(reshaped_arr)

[[10 15]
 [20 25]
 [30 35]
 [40 45]]


##5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
##• Extract the sub-matrix containing the last two rows and first two columns.
##• Replace all elements greater than 4 with 0.

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#Extract the sub-matrix containing the last two rows and first two columns.
print(arr[1:,:2])
print(arr[:2,:2])
#Replace all elements greater than 4 with 0.
arr[arr>4]=0
print("Repalced array:\n ", arr)

[[4 5]
 [7 8]]
[[1 2]
 [4 5]]
Repalced array:
  [[1 2 3]
 [4 0 0]
 [0 0 0]]


In [ ]:
arr=np.where(arr>4,0,arr)
print(arr)

[[1 2 3]
 [4 0 0]
 [0 0 0]]


#6.Create two 1D arrays:
#• a = np.array([1, 2, 3])
#• b = np.array([4, 5, 6])
#• Perform element-wise addition, multiplication, and division.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition :\n" ,np.add(a,b))
print("Multiplication :\n",np.multiply(a,b))
print("Division :\n",np.divide(a,b))

Addition :
 [5 7 9]
Multiplication :
 [ 4 10 18]
Division :
 [0.25 0.4  0.5 ]


# 7.Create a random NumPy array of size (4, 4). Compute:
#• Mean of each column.
#• Maximum value of the entire array.
# Sum of all elements.

In [ ]:
arr=np.random.rand(4,4)
print(arr)
print(" Mean: ",np.mean(arr,axis=0))
print("Maximum value of the entire array: ",np.max(arr))
print("Sum of all elements: ",np.sum(arr))

[[0.2655007  0.86907183 0.37966122 0.47126459]
 [0.37262006 0.95681351 0.2227788  0.97003987]
 [0.07830546 0.72856955 0.19093977 0.53143999]
 [0.34644392 0.38012326 0.25104239 0.31884197]]
 Mean:  [0.26571754 0.73364454 0.26110554 0.57289661]
Maximum value of the entire array:  0.97003987394721
Sum of all elements:  7.333456893593979


# 8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [ ]:
array=np.array([1,2,3,4])
array += 10
print("Addition with 10 :\n ",array)
array *= 2
print("Multiply with 2 :\n",array)

Addition with 10 :
  [11 12 13 14]
Multiply with 2 :
 [22 24 26 28]


# 9.Perform advanced slicing and indexing on a 3D array.
#Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following:
#• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
#• Extract the first two rows and the last three columns from each "layer."
#• Replace all elements divisible by 3 with -1.

In [11]:
a=np.random.randint(1,100,(3,4,5))
print(a)
# Extract the second "layer" (i.e., the second 2D array) in the first dimension.
print("Second Layer :\n", a[1])
#Extract the first two rows and the last three columns from each "layer."
print("First two rows and last three coloums:\n",a[:,:2,2:])
#Replace all elements divisible by 3 with -1.
print("Repalced array :\n",np.where(a%3==0,-1,a))

[[[80 31 84 53 28]
  [14 25 47 65  1]
  [71 38 35 14 86]
  [ 4 15 66 47 94]]

 [[16 44 18 18  1]
  [51  9  1 71  2]
  [89 42 73 62  6]
  [70 58 33 38 57]]

 [[89 99 77  8 84]
  [34  6 54 87 10]
  [24 52 71 10 87]
  [ 7  2 49  3 45]]]
Second Layer :
 [[16 44 18 18  1]
 [51  9  1 71  2]
 [89 42 73 62  6]
 [70 58 33 38 57]]
First two rows and last three coloums:
 [[[84 53 28]
  [47 65  1]]

 [[18 18  1]
  [ 1 71  2]]

 [[77  8 84]
  [54 87 10]]]
Repalced array :
 [[[80 31 -1 53 28]
  [14 25 47 65  1]
  [71 38 35 14 86]
  [ 4 -1 -1 47 94]]

 [[16 44 -1 -1  1]
  [-1 -1  1 71  2]
  [89 -1 73 62 -1]
  [70 58 -1 38 -1]]

 [[89 -1 77  8 -1]
  [34 -1 -1 -1 10]
  [-1 52 71 10 -1]
  [ 7  2 49 -1 -1]]]


# 10. Work with broadcasting and advanced operations in NumPy.
#Create a NumPy array arr of shape (3, 3) with random integers between  
#1 and 20. Perform the following:
#• Subtract the mean of each row from its respective elements (row-wise
#normalization).
#• Create a new array by squaring all the elements in arr.
#• Find the indices of the top 3 maximum values in the entire array.

In [12]:
arr = np.random.randint(1, 21, size=(3, 3))
print("Original Array:")
print(arr)
flattened_arr = arr.ravel()
# Get the indices of the elements sorted in ascending order
sorted_indices = np.argsort(flattened_arr)
# Select the top 3 indices (top 3 maximum values are at the end of the sorted indices)
top_3_indices_flattened = sorted_indices[-3:]
#Convert the flattened indices back to 2D indices
top_3_indices = np.unravel_index(top_3_indices_flattened, arr.shape)
print("\nIndices of the Top 3 Maximum Values:")
print(top_3_indices)


Original Array:
[[ 3 20 17]
 [12  8 12]
 [ 5 10 19]]

Indices of the Top 3 Maximum Values:
(array([0, 2, 0]), array([2, 2, 1]))
